import budgetTracker from './Assets/images/budgetTracker.png';
import lostFound from './Assets/images/lostFound.png';
import noteTaker from './Assets/images/noteTaker.png';
import reactEmployeeDirectory from './Assets/images/reactEmployeeDirectory.png';
import techBlog from './Assets/images/techBlog.png';
import workoutTracker from './Assets/images/workoutTracker.png';
import technologies from './technologies';

const {
	react,
	javascript,
	github,
	git,
	nodejs,
	npm,
	bootstrap,
	css,
	html,
	heroku,
	mysql,
	mongodb,
} = technologies;

const projects = [
	{
		id: 1,
		name: 'React Employee Directory',
		img: reactEmployeeDirectory,
		repoURL: 'https://github.com/Youngin9210/REACT-EmployeeDirectory',
		deployedURL: 'https://youngin9210.github.io/REACT-EmployeeDirectory/',
		details: 'Details go here',
		technologies: [
			react,
			javascript,
			github,
			git,
			nodejs,
			npm,
			bootstrap,
			css,
			html,
		],
	},
	{
		id: 2,
		name: 'Budget Tracker',
		img: budgetTracker,
		repoURL: 'https://github.com/Youngin9210/Budget-Tracker',
		deployedURL: 'https://protected-stream-94143.herokuapp.com/',
		details: 'Details go here',
		technologies: [
			javascript,
			github,
			git,
			nodejs,
			npm,
			bootstrap,
			css,
			html,
			heroku,
			mongodb,
		],
	},
	{
		id: 3,
		name: 'Workout Tracker',
		img: workoutTracker,
		repoURL: 'https://github.com/Youngin9210/Workout-Tracker',
		deployedURL:
			'https://fierce-inlet-72161.herokuapp.com/?id=60a81b79b60c910015bdb426',
		details: 'Details go here',
		technologies: [
			javascript,
			github,
			git,
			nodejs,
			npm,
			bootstrap,
			css,
			html,
			heroku,
			mongodb,
		],
	},
	{
		id: 4,
		name: 'Lost & Found',
		img: lostFound,
		repoURL: 'https://github.com/Youngin9210/Lost-Found',
		deployedURL: 'https://glacial-fortress-45860.herokuapp.com/',
		details: 'Details go here',
		technologies: [
			javascript,
			github,
			git,
			nodejs,
			npm,
			bootstrap,
			css,
			html,
			heroku,
			mysql,
		],
	},
	{
		id: 5,
		name: 'Tech Blog',
		img: techBlog,
		repoURL: 'https://github.com/Youngin9210/Tech-Blog',
		deployedURL: 'https://nameless-basin-78183.herokuapp.com/',
		details: 'Details go here',
		technologies: [
			javascript,
			github,
			git,
			nodejs,
			npm,
			bootstrap,
			css,
			html,
			heroku,
			mysql,
		],
	},
	{
		id: 6,
		name: 'Note Taker',
		img: noteTaker,
		repoURL: 'https://github.com/Youngin9210/Note-Taker',
		deployedURL: 'https://youngin9210.github.io/Weather-Dashboard/',
		details: 'Details go here',
		technologies: [
			javascript,
			nodejs,
			npm,
			css,
			html,
			bootstrap,
			github,
			git,
			heroku,
		],
	},
];

export default projects;
